repo_full_name,issue_id,number,title,body,user_login,user_id,state,locked,comments_count,created_at,updated_at,closed_at,labels,reactions_total,reactions_plus1,reactions_minus1,reactions_laugh,reactions_hooray,reactions_confused,reactions_heart
rasbt/python-machine-learning-book,2801761507,108,Python ML,,MiAlesia,147939963,closed,False,1,2025-01-21T12:50:17+00:00,2025-01-21T19:06:36+00:00,2025-01-21T19:06:36+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,2497786488,102,.py learning book,,28gyeltshen,151841613,closed,False,1,2024-08-30T16:50:53+00:00,2024-08-30T16:53:37+00:00,2024-08-30T16:53:37+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,2217965141,101,Update README.md,"Hi,
I have created a PR in the general question section about the machine learning roadmap. I hope you will find this helpful for your repository and will merge this, Thank you.",jivan84,118162251,open,False,1,2024-04-01T10:08:56+00:00,2024-04-01T10:10:28+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,2128799130,100,"Machine learning
",,Donmakabz,159147208,closed,False,1,2024-02-11T02:18:41+00:00,2024-02-11T02:20:09+00:00,2024-02-11T02:19:00+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,2018536828,99,Python machine learning,,HowsounSJ,36335896,open,False,1,2023-11-30T12:17:41+00:00,2023-11-30T12:19:25+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,1673997974,98,Graph of curve is misleading,"To be accurate the picture that represents the generic graph does not represent a function, actually it is not a function since there are instances where for a given X-value there is more than one Y-value. In mathematics a graph is a help and a guide but it should not be misleading",Fractal2017,29259883,open,False,1,2023-04-19T00:34:29+00:00,2023-04-19T00:35:41+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,1347688374,96,Added a helpful link,"Hey, I have added a helpful reference link for the python tutorial in the Additional Resources & Further Reading section that I think will best add to your content and give your readers a more diverse understanding of the topic. I hope you will like this. Thank you.",bikashdaga09,111844391,closed,False,3,2022-08-23T10:15:14+00:00,2024-04-11T19:07:46+00:00,2022-08-23T11:32:52+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,1232169657,95,why this is the self.eta*X.T.dot(errors) rather than the -self.eta*X.T.dot(errors),"thanks for your book,i have a small question by reading chapter 2
by its defination , i think the negative symbol is necessary.
![image](https://user-images.githubusercontent.com/56285119/167798690-2404ab7f-2c21-4bec-96a4-cc6acbeb04ef.png)
",python-users,56285119,open,False,1,2022-05-11T07:58:55+00:00,2022-05-11T16:41:43+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,948006678,94,docs: Fix a few typos,"There are small typos in:
- code/ch01/README.md
- code/ch12/optional-streamlined-neuralnet.py
- faq/ai-and-ml.md
- faq/naive-bayes-vartypes.md
- faq/scale-training-test.md

Fixes:
- Should read `were` rather than `weere`.
- Should read `occurrences` rather than `occurences`.
- Should read `laborious` rather than `labrorious`.
- Should read `initializing` rather than `initalizing`.
- Should read `distribution` rather than `distribtion`.
- Should read `dataset` rather than `datast`.



Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md",timgates42,47873678,closed,False,1,2021-07-19T20:36:04+00:00,2021-07-30T13:18:39+00:00,2021-07-30T13:18:39+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,923881240,93,[QUESTION] in ch3.py line 64,"in line 64 we use this line to calculate the number of misclassified samples  `print('Misclassified samples: %d' % (y_test != y_pred).sum())`

I think that in some cases it might not give the correct number, consider 
y_test = [2, 2, 2]  meaning the true labels are 2
y_perd = [0, 0, 0] meaning the predicted labels are 0

The output will be 6 ! even though only 3 samples were misclassified !",naty55,64107292,closed,False,3,2021-06-17T12:42:49+00:00,2021-06-18T09:54:49+00:00,2021-06-17T17:12:51+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,830773111,92,How to Use the code files,"Hi, I am extremely new to Python and I understand how to write basic commands and stuff.
I got the Code files for the book but I am not able to understand how to use them for learning.
All of them seem to be in Text format.
How can I use them as code to make a new file in which I can just have the Code instead of all the text.
I just wanted to see how the code runs but I am unable to understand what this code is and how to extract things which I want instead of having to remove all the """" and /n and other formatting elements.
Thanks.
![text_code](https://user-images.githubusercontent.com/80556946/111015003-9689f280-8374-11eb-9ae0-c3b845df09b3.PNG)
",Gomzzz93,80556946,closed,False,2,2021-03-13T01:51:49+00:00,2021-03-13T15:30:17+00:00,2021-03-13T01:58:08+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,783246225,91,Hello Kaggle! It is a guide for new kaggler,"https://github.com/stevekwon211/Hello-Kaggle
It is a Kaggle Guide Document for someone who is new at Kaggle!",stevekwon211,61633137,open,False,0,2021-01-11T10:23:57+00:00,2021-01-11T10:23:57+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,722901970,90,Update .gitignore,,AliHaider20,42317018,open,False,0,2020-10-16T04:50:43+00:00,2020-10-16T04:50:43+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,712477927,89,I have added a Data Science Interview Questions and answers PDF... Please merge it into your Repo,,Nitish-McQueen,54181907,closed,False,1,2020-10-01T04:53:01+00:00,2020-10-01T16:11:41+00:00,2020-10-01T16:11:41+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,712410863,88,a small contribution,,Gopalbansal8106,68762809,closed,False,0,2020-10-01T01:57:06+00:00,2024-06-17T11:55:51+00:00,2024-06-17T07:06:30+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,712201295,87,should combine teachable machine,,Yash1975,72147910,open,False,0,2020-09-30T19:03:07+00:00,2020-09-30T19:03:07+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,676142671,86,Create data_science,"data science
https://github.com/ossu/data-science

https://thenextweb.com/growth-quarters/2020/08/08/5-free-resources-every-data-scientist-should-start-using-today-syndication/",Sanulone,50818256,closed,False,0,2020-08-10T13:36:44+00:00,2020-08-10T16:09:23+00:00,2020-08-10T16:09:23+00:00,,1,1,0,0,0,0,0
rasbt/python-machine-learning-book,675596331,85,Machine Learning (Python),,Chavez99,64931974,closed,False,0,2020-08-08T22:13:47+00:00,2020-08-10T15:11:01+00:00,2020-08-10T15:11:01+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,663174801,84,"ValueError: operands could not be broadcast together with shapes (200,) (30000,)","I am working on a finite element code in python. It is originally for the diffusion equation but I want to modify it for the wave equation and include a ricker source term. I tried adding the source term and it produces an error. Below is the code and error

from IPython import display
from matplotlib.tri import Triangulation, LinearTriInterpolator

deltat = 0.001
numIterations = 30
mass = numpy.zeros((NPOINTS,NPOINTS))
stiffness = numpy.zeros((NPOINTS,NPOINTS))
phi  = numpy.zeros((NPOINTS,))
phi_old = numpy.zeros((NPOINTS,))

f0= 5      # Center frequency Ricker-wavelet
q0= 100       # Maximum amplitude Ricker-Wavelet
t=np.arange(0,numIterations,deltat)     # Time vector

tau=np.pi*f0*(t-1.5/f0)
q=q0*(1.0-2.0*tau**2.0)*np.exp(-tau**2)


xi = np.linspace(0, L, 200)
yi = np.linspace(0, H, 200)
Xi, Yi = np.meshgrid(xi, yi)

updateMatrix(mass,stiffness,phi)
mat = mass/deltat + stiffness
triang = Triangulation(points[:,0], points[:,1])

for iteration in range(1,numIterations+1):
    phi_old = phi
        
    rhs = numpy.dot(mass/deltat, phi_old)
    rhs = rhs + q
    phi = numpy.linalg.solve(mat,rhs)
interpolator = LinearTriInterpolator(triang, phi)
zi = interpolator(Xi, Yi)
fig1 = pylab.figure(1)
pylab.imshow(zi)

fig2 = pylab.figure(2)
xanal, yanal = analytical(numIterations*deltat)
pylab.plot(xanal,yanal,""-"")
pylab.plot(Xi[100,:],zi[100,:])
fig2.savefig(""comparison.png"",format=""PNG"")


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-34-3ab2f39f86f8> in <module>
     29 
     30     rhs = numpy.dot(mass/deltat, phi_old)
---> 31     rhs = rhs + q
     32     phi = numpy.linalg.solve(mat,rhs)
     33 interpolator = LinearTriInterpolator(triang, phi)

ValueError: operands could not be broadcast together with shapes (200,) (30000,) ",donet3088,34796954,closed,False,1,2020-07-21T17:09:55+00:00,2020-08-10T22:01:40+00:00,2020-08-10T22:01:40+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,660389033,83,Python Machine learning ,,Jesutomi-olatunde,68343227,closed,False,0,2020-07-18T21:23:05+00:00,2020-07-20T13:02:32+00:00,2020-07-20T13:02:32+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,567211757,82,IndexError: too many indices for array in CH-5 PCA Plot Code ,"I am having an issue in executing the for generating the graph of the PCA in Chapter-5 of the book Python Machine Learning. I tried debugging but I am not able to understand what the problem in the code is.
![issue1](https://user-images.githubusercontent.com/15856787/74785512-81798780-5278-11ea-8f06-52e1de87e6a6.png)
Kindly provide support for this issue.",somesh636,15856787,closed,False,3,2020-02-18T23:01:53+00:00,2020-02-22T18:20:34+00:00,2020-02-22T18:20:34+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,545468688,81,Notebook error,"Opening the first chapter file ch01.ipynb result in the following error:

""Unreadable Notebook: /home/antonio/libro-machine-learning/ch01.ipynb NotJSONError(""Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang..."")""

python version: 3.7 from anaconda distribution.",einsteniano4000,13972146,closed,False,2,2020-01-05T21:23:45+00:00,2020-01-05T21:58:47+00:00,2020-01-05T21:29:01+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,507746558,80,library,,binit00,44134737,open,False,1,2019-10-16T09:59:54+00:00,2019-10-16T09:59:56+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,464012588,79,Merge pull request #1 from rasbt/master,update,waith,7114194,closed,False,0,2019-07-04T01:05:10+00:00,2019-07-04T07:07:48+00:00,2019-07-04T07:07:48+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,438071757,78,Chapter 15: Padding modes figure,"On page 500 (second edition: September 2017) there is a figure illustrating Full, Same and Valid padding and how the pixel patches map to the feature maps. 

The feature map of the valid padding example is only 2x2. It specifies a 5x5 pixel input, 3x3 filter and a stride of 1. The feature map should be of size 3x3.",tynowell,4519360,closed,False,1,2019-04-28T16:00:19+00:00,2019-04-28T20:14:26+00:00,2019-04-28T20:14:26+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,399517922,77,AttributeError: 'SGDClassifier' object has no attribute 'max_iter',"Hello! Thank you for this amazing gift to everyone!

My issue is with Chapter 9's movie_classifier_with_update via `python app.py.` I am able to enter my sample review and get predicted class label and probability. The issue arises when I click ""Correct""/""Incorrect"" for the classification.

It is almost assuredly due to the issue of versions of Python (3.5 needed) and Sklearn (0.19 needed) as indicated here: https://www.pythonanywhere.com/forums/topic/11716/

It'd be nice to keep this current though and I will send a PR if I ever figure out how to update it for Python 3.6 and Sklearn 0.20!

![image](https://user-images.githubusercontent.com/23364185/51207361-37351280-18d0-11e9-8384-2b56efea59ba.png)
",dfiorino,23364185,closed,False,1,2019-01-15T20:17:04+00:00,2019-01-16T15:48:49+00:00,2019-01-16T15:48:49+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,398781378,76,"ValueError: operands could not be broadcast together with shapes (400,2) (400,) ","

Dear concerns : I am extracting features from wav , using PLP , this ( Pyhton 3.6 -Anaconda Spyder ) after execute i am facing error in this line 

  File ""C:\ProgramData\Anaconda3\lib\site-packages\sidekit\frontend\features.py"", line 399, in power_spectrum
    ahan = framed[start:stop, :] * window

ValueError: operands could not be broadcast together with shapes (400,2) (400,) 
```
#!usr/bin/python
import numpy.matlib
import scipy
from scipy.fftpack.realtransforms import dct
from sidekit.frontend.vad import pre_emphasis
from sidekit.frontend.io import *
from sidekit.frontend.normfeat import *
from sidekit.frontend.features import *
import scipy.io.wavfile as wav
import numpy as np



def readWavFile(wav):
        #given a path from the keyboard to read a .wav file
        #wav = raw_input('Give me the path of the .wav file you want to read: ')
        inputWav = 'C:/Speech_Processing/2-Speech_Signal_Processing_and_Classification-master/feature_extraction_techniques'+wav
        return inputWav
#reading the .wav file (signal file) and extract the information we need
def initialize(inputWav):
        rate , signal  = wav.read(readWavFile(inputWav)) # returns a wave_read object , rate: sampling frequency
        sig = wave.open(readWavFile(inputWav))
        # signal is the numpy 2D array with the date of the .wav file
        # len(signal) number of samples
        sampwidth = sig.getsampwidth()
        print ('The sample rate of the audio is: ',rate)
        print ('Sampwidth: ',sampwidth)
        return signal ,  rate
def PLP():
        folder = input('Give the name of the folder that you want to read data: ')
        amount = input('Give the number of samples in the specific folder: ')
        for x in range(1,int(amount)+1):
                wav = '/'+folder+'/'+str(x)+'.wav'
                print (wav)
                #inputWav = readWavFile(wav)
                signal,rate = initialize(wav)
                #returns PLP coefficients for every frame
                plp_features = plp(signal,rasta=True)
                meanFeatures(plp_features[0])
#compute the mean features for one .wav file (take the features for every frame and make a mean for the sample)
def meanFeatures(plp_features):
        #make a numpy array with length the number of plp features
        mean_features=np.zeros(len(plp_features[0]))
        #for one input take the sum of all frames in a specific feature and divide them with the number of frames
        for x in range(len(plp_features)):
                for y in range(len(plp_features[x])):
                        mean_features[y]+=plp_features[x][y]
        mean_features = (mean_features / len(plp_features))
        print (mean_features)

def main():
        PLP()

main()
```
",kaleemdhu,33798743,open,False,0,2019-01-14T08:02:01+00:00,2019-01-14T08:02:01+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,392107578,75,Add links to Deepnote,"I prefer to work with Deepnote over NbViewer, because it allows you to interactively edit the files online and save your work. Added links to launch the notebooks in Deepnote in case anyone else wants to play around with the code.",jirkalhotka,16825133,open,False,7,2018-12-18T11:12:45+00:00,2019-08-02T19:47:15+00:00,,,1,1,0,0,0,0,0
rasbt/python-machine-learning-book,382195015,74,Chapter 8: Shuffling the DataFrame in newer versions of pandas,"Just a note in case it's helpful to anyone else - I seemed to be getting 100% accuracy with the on-line sentiment analysis classifier (pages 246-246), but it turned out to be because the code used to shuffle the dataset before exporting it to CSV on page 235 hadn't worked.

In the version of pandas I'm using (0.23.4), it looks like `df.index.values` is needed in order to get the indexes of a DataFrame as a list. So, this:

`df = df.reindex(np.random.permutation(df.index))`

now needs to be this:

`df = df.reindex(np.random.permutation(df.index.values))`

Hope that helps someone!",steveneale,37803830,open,False,1,2018-11-19T12:34:35+00:00,2022-10-18T17:49:02+00:00,,,2,2,0,0,0,0,0
rasbt/python-machine-learning-book,377020412,73,ValueError: operands could not be broadcast together with shapes,,hamsterLee,41764574,closed,False,1,2018-11-03T03:55:44+00:00,2018-11-04T21:13:11+00:00,2018-11-04T21:13:11+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,343380249,72,mlxtend no longer has tf_classifier,"I wanted to run your code that compares TensorFlow with SKLearn but it no longer works. 
https://github.com/rasbt/python-machine-learning-book/blob/master/faq/tensorflow-vs-scikitlearn.md

In addition, your mlxtend package no longer has tf_classifier and consequently no TfSoftMaxRegression.

Would you have an updated resource by any chance?",anyaconda,33555812,closed,False,3,2018-07-22T06:05:52+00:00,2018-07-24T03:55:54+00:00,2018-07-24T03:55:54+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,332351752,71,ch.06(Tuning hyperparameters via grid search),"I'm now learning machine learning using the Japanese translation of this book, and when I run this program, I always get stuck on the part using sklearn.svm.

When the program do the part""gs=gs.fit(X_train,y_train)"", it always show the past two graphs infinitely. I don't know the reason, so tell me what may be the cause.

My PC's spec:
Window10, python3.6.5, scikit-learn0.19.1",yuusukekoyano,38643946,open,False,4,2018-06-14T10:55:37+00:00,2018-06-15T23:30:50+00:00,,question,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,330939139,70,i need to find somebody who can automate a trading strategy,"im new to the site, if you can or cant if you could send me in the right direction it would greatly appreciated",MrReherfx,40132580,closed,False,1,2018-06-10T04:21:37+00:00,2018-06-10T15:40:37+00:00,2018-06-10T15:40:37+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,282978771,69,Merge pull request #1 from rasbt/master,Update fork,RITESHMOHAPATRA,17006872,closed,False,0,2017-12-18T18:32:43+00:00,2017-12-18T18:32:53+00:00,2017-12-18T18:32:53+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,278687760,68,Couldn't get desired output from Adaptive linear neuron implementation ,"Hi,
I was trying out one of the example in `Chapter2`, under title: **Implementing an adaptive linear neuron in Python** ([Link to notebook](https://github.com/rasbt/python-machine-learning-book/blob/master/code/ch02/ch02.ipynb)). 
The problem is when I plot decision boundaries, whole area is shown red.
<img width=""639"" alt=""screen shot 2017-12-02 at 22 21 25"" src=""https://user-images.githubusercontent.com/13061583/33516532-3714e45a-d7af-11e7-8559-33cb9a86f3dd.png"">

When I change `output = self.activation(X)` to `output = self.predict(X)`inside `fit` function, the problem seems to be gone.
<img width=""637"" alt=""screen shot 2017-12-02 at 22 21 00"" src=""https://user-images.githubusercontent.com/13061583/33516535-49e7e7bc-d7af-11e7-954d-13899e2287ce.png"">

Is there an issue with the code or the code is correct and I made some other mistake while implementing? 

Thanks
Sohaib",sohaibfarooqi,13061583,closed,False,1,2017-12-02T14:24:27+00:00,2021-05-21T12:12:42+00:00,2021-05-21T12:12:42+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,269390585,67,Acm,acm badge,SUSHANT12PRABHU,23032355,closed,False,1,2017-10-29T11:16:09+00:00,2017-10-29T19:16:27+00:00,2017-10-29T19:16:27+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,269390531,66,Pep8,"fixes
",SUSHANT12PRABHU,23032355,closed,False,1,2017-10-29T11:15:10+00:00,2017-10-29T19:16:19+00:00,2017-10-29T19:16:19+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,269390492,65,ru isbn,ru isbn,SUSHANT12PRABHU,23032355,closed,False,1,2017-10-29T11:14:19+00:00,2017-10-29T19:16:10+00:00,2017-10-29T19:16:10+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,265504172,64,fix small typo,,sourcesoft,608906,closed,False,1,2017-10-14T16:31:57+00:00,2017-10-14T18:22:24+00:00,2017-10-14T18:22:24+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,251210339,63,TypeError: can't multiply sequence by non-int of type 'float',"I am getting this error at the np.dot for the Iris data set. Can you explain the solution ? 

Following is traceback :
Traceback (most recent call last):
  File ""Perceptron.py"", line 61, in <module>
    ppn.train(x, y)
  File ""Perceptron.py"", line 24, in train
    update = self.eta * (target - self.predict(xi))
  File ""Perceptron.py"", line 35, in predict
    return np.where(self.net_input(X) >= 0.0, 1, -1)
  File ""Perceptron.py"", line 32, in net_input
    return np.dot(X, self.w_[1:]) + self.w_[0]",sprakashsingh,21097918,open,False,2,2017-08-18T10:54:56+00:00,2017-08-18T15:29:24+00:00,,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,249847324,62,Merge pull request #1 from rasbt/master,cat movieclassifier files into notebook for easier reference,fcui,28622018,closed,False,0,2017-08-13T02:19:00+00:00,2017-08-13T02:20:21+00:00,2017-08-13T02:20:21+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,246592515,61,pep8 fixes,,rasbt,5618407,closed,False,1,2017-07-30T16:02:45+00:00,2017-07-30T16:04:06+00:00,2017-07-30T16:04:06+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,246583365,60,Implementation of AdalineSGD,"Hi,

First of all, thanks for your nice book, _Python Machine Learning_

I began to read it right now and I am wondering one thing about the implementation of **AdalineSGD** mentioned in book
```
    def fit(self, X, y):
        
        self._initialize_weights(X.shape[1])
        self.cost_ = []
        for i in range(self.n_iter):
            if self.shuffle:
                X, y = self._shuffle(X, y)
            cost = []
            for xi, target in zip(X, y):
                cost.append(self._update_weights(xi, target))
            avg_cost = sum(cost) / len(y)
            self.cost_.append(avg_cost)
        return self

    def _update_weights(self, xi, target):
        """"""Apply Adaline learning rule to update the weights""""""
        output = self.net_input(xi)
        error = (target - output)
        self.w_[1:] += self.eta * xi.dot(error)
        self.w_[0] += self.eta * error
        cost = 0.5 * error**2
        return cost        

```
I think, the way to update self.w_[1:] in _AdalineSGD_ is in fact the same as implementation of the _batch AdalineGD_, just implemented in different ways
```
            output = self.activation(X)
            errors = (y - output)
            self.w_[1:] += self.eta * X.T.dot(errors)
```
IMO, _self.eta * X.T.dot(errors)_ operates on entire matrix **X** in _AdalineGD_, however _AdalineSGD_ operates on row by row via _**for**_-loop (_for xi, target in zip(X, y)_) of the same **X**. It doesn't reflect the essential diff between _AdalineGD_ and _AdalineSGD_ as you mentioned in book",idavollen,1467270,closed,False,10,2017-07-30T13:18:55+00:00,2017-08-03T09:17:39+00:00,2017-08-03T09:17:39+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,246573102,59,Solving little errors while reading the book,This is a fix of little errors and warnings i had with Python 3.6.2 and NumPy 1.13.1,AlexanderKunkel,30548729,closed,False,2,2017-07-30T09:29:09+00:00,2017-07-30T14:35:16+00:00,2017-07-30T14:35:16+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,246540012,58,typo in chapter 12,"In [this file](https://github.com/rasbt/python-machine-learning-book/blob/master/code/ch12/ch12.ipynb), the code loads the names as 

    labels_path = os.path.join(path, 
                               '%s-labels-idx1-ubyte' % kind)
    images_path = os.path.join(path, 
                               '%s-images-idx3-ubyte' % kind)

However the linked .gz file has the names with a period, not a hyphen. It should be


    labels_path = os.path.join(path, 
                               '%s-labels.idx1-ubyte' % kind)
    images_path = os.path.join(path, 
                               '%s-images.idx3-ubyte' % kind)

https://www.reddit.com/r/learnpython/comments/6qc9t1/path_to_existing_file_in_root_folder_not_found_on/",novel-yet-trivial,23124853,closed,False,6,2017-07-29T19:17:38+00:00,2017-07-30T03:14:12+00:00,2017-07-30T03:14:07+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,245411937,57,question about in [29],"dear sir..
i try to study Machine Learning through your book 『Python Machine Learning』, and it's very nick book!
i can't understand how you to set up 『param_grid』
i try to get the information from sklearn but it just say『dict or list of dictionaries』
even the sample , it just write 『param_grid=....』
So ... about the 『param_grid』 how do i set it up!
i am sorry my english is a little week!
i hope i can let you know my question and thank you very much!",shaoeChen,28851695,closed,False,1,2017-07-25T14:02:17+00:00,2017-07-29T21:38:13+00:00,2017-07-29T21:38:13+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,243957846,56,Images,,Yagami360,25688193,closed,False,0,2017-07-19T08:12:52+00:00,2017-07-19T08:15:24+00:00,2017-07-19T08:15:24+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,241718859,55,ru isbn,,rasbt,5618407,closed,False,0,2017-07-10T13:50:02+00:00,2017-07-10T13:50:23+00:00,2017-07-10T13:50:23+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,241140961,54,add acm badge,,rasbt,5618407,closed,False,0,2017-07-07T02:39:26+00:00,2017-07-07T02:42:54+00:00,2017-07-07T02:42:54+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,240525920,53,update syntax to keras 2,,rasbt,5618407,closed,False,0,2017-07-05T02:54:14+00:00,2017-07-05T02:54:19+00:00,2017-07-05T02:54:19+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,240512425,52,Typo/Clarification on Ch02.ipynb,"There is an _Additional Note (1)_ section where it says: "" If all the weights are initialized to 0, only the scale of the weight vector, not the direction.""

Seems there is some missing meaning in that sentence.  Was wondering if you could correct it please.  Thank you very much!",mastash3ff,3743196,closed,False,1,2017-07-05T00:16:51+00:00,2017-07-05T01:37:30+00:00,2017-07-05T01:37:30+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,239869723,51,python crushes when running theano code,"Hi 

I am trying to run the following code from the book in jupyter notebook with everything updated. However, every time python crushes and the kernel restarts. Everything is fine before this point. Any thought?
ps. using 32bit and gpu, tried dmatrix, no luck
chapter 13

import numpy as np
x = T.dmatrix(name='x')
x_sum = T.sum(x, axis=0)
calc_sum = theano.function(inputs=[x],outputs=x_sum)
ary = [[1,2,3],[1,2,3]]
print('column sum:',calc_sum(ary))",BingKong1988,25316664,closed,False,7,2017-06-30T19:32:42+00:00,2017-07-06T16:16:48+00:00,2017-07-06T16:16:48+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,237728668,50,AttributeError: Can't get attribute 'tokenizer_porter' on <module '__main__' (built-in)>,"trying to run gs_lr_tfidf.fit(X_train, y_train) and got the AttributeError

Running on jupyter notebook, python 3.5",BingKong1988,25316664,closed,False,7,2017-06-22T04:24:44+00:00,2022-11-09T04:14:50+00:00,2017-06-22T17:15:17+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,225324102,49,"Windows 10, ImportError: cannot import name 'plot_decision_regions'","Hello,

I was trying to execute the code:

```
%matplotlib inline
from sklearn.linear_model import LogisticRegression 
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from mlxtend.evaluate import plot_decision_regions

iris = load_iris()
y, X = iris.target, iris.data[:, [0, 2]]  # only use 2 features
lr = LogisticRegression(C=100.0, 
                        class_weight=None, 
                        dual=False, 
                        fit_intercept=True,
                        intercept_scaling=1, 
                        max_iter=100, 
                        multi_class='multinomial', 
                        n_jobs=1,
                        penalty='l2', 
                        random_state=1, 
                        solver='newton-cg', 
                        tol=0.0001,
                        verbose=0, 
                        warm_start=False)
lr.fit(X, y)
plot_decision_regions(X=X, y=y, clf=lr, legend=2)
plt.xlabel('sepal length')
plt.ylabel('petal length')
plt.show()
```

but it returned following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-9b78ac9a656a> in <module>()
      3 from sklearn.datasets import load_iris
      4 import matplotlib.pyplot as plt
----> 5 from mlxtend.evaluate import plot_decision_regions
      6 
      7 iris = load_iris()

ImportError: cannot import name 'plot_decision_regions'
```

I installed `mlxtend` package. What am I doing wrong? Could You help me? Thanks in advance!",Megaloxantha,28221336,closed,False,2,2017-04-30T12:30:18+00:00,2017-04-30T18:22:31+00:00,2017-04-30T17:41:49+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,220480391,48,use probas in roc_auc_score and add note about memory view,,rasbt,5618407,closed,False,0,2017-04-09T16:04:42+00:00,2017-04-09T16:05:06+00:00,2017-04-09T16:05:06+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,219776883,47,Issues when installing Keras on Windows 10 64bit machines,"Hi,

I had an issue when installing Keras on Windows 10 64bit machine (as described in ch13) but this did not work. I have posted the solution in a step by step here in this blog post:

[install keras on windows 10 x64 bit machine ](http://www.mostafaelzoghbi.com/2017/04/how-to-install-keras-on-windows-10-64.html
)
@rasbt : feel free to add it to the notes of the labs in GitHub.

Thanks.

",melzoghbi,11993393,closed,False,1,2017-04-06T03:30:43+00:00,2017-04-10T05:08:28+00:00,2017-04-10T05:08:28+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,218709817,46,Missing word (have) and typos,,Naereen,11994719,closed,False,3,2017-04-01T17:17:21+00:00,2017-04-01T21:38:28+00:00,2017-04-01T19:19:04+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,213503463,45,run chapters with most recent libraries 2017-03-10,,rasbt,5618407,closed,False,0,2017-03-11T04:02:55+00:00,2017-03-11T04:03:01+00:00,2017-03-11T04:03:01+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,212224485,44,Adding the iris.data file back into the repo,"Can the iris.data file be added back into the repo on master?

Here's the last version I believe:
https://github.com/rasbt/python-machine-learning-book/blob/194e34f245abb97f53d0e72166ab6785d01a1e94/code/datasets/iris/iris.data

Thanks again!",jay-johnson,4564911,closed,False,1,2017-03-06T19:29:07+00:00,2017-03-06T23:05:13+00:00,2017-03-06T23:05:13+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,209132933,43,Fixed minor typos.,"Fixed a couple of typos and removed pronoun shifts in order to maintain a consistent point of view (first person plural, ""we"".)",clarkzinzow,7699919,closed,False,1,2017-02-21T12:36:37+00:00,2017-02-21T15:04:51+00:00,2017-02-21T15:04:50+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,201743205,42,jupiter -> jupyter,,emptyr1,2340951,closed,False,1,2017-01-19T01:48:15+00:00,2017-01-19T04:33:31+00:00,2017-01-19T04:33:30+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,200875689,41,Plotting iris data in Ch02 assumes that the data is in a particular order,"In chapter 2, where the iris data is plotted on a scatterplot,

    # extract sepal length and petal length
    X = df.iloc[0:100, [0, 2]].values
    
    # plot data
    plt.scatter(X[:50, 0], X[:50, 1],
                color='red', marker='o', label='setosa')
    plt.scatter(X[50:100, 0], X[50:100, 1],
                color='blue', marker='x', label='versicolor')

it is simply assumed that the first 50 rows belong to the label setosa, and the next 50 to versicolor. The scatterplot should be generated using the labels(which are in the 5th column of the dataset)",medakk,10536745,closed,False,1,2017-01-15T15:41:06+00:00,2017-01-15T16:03:01+00:00,2017-01-15T16:03:01+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,199153130,40,pip install SomePackge,"Hello, 

I currently facing the attached issue. 

Is this package only available to Linux users? I'm on Windows. 

![somepackage installation error](https://cloud.githubusercontent.com/assets/17061696/21712948/5b963436-d432-11e6-963f-309367201c44.jpg)
",NahidRM,17061696,closed,False,5,2017-01-06T09:06:17+00:00,2017-01-07T18:32:20+00:00,2017-01-06T16:11:45+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,198622858,39,add missing line to cell 16/17,fixes #38 ,rasbt,5618407,closed,False,0,2017-01-04T03:27:19+00:00,2017-01-04T03:27:24+00:00,2017-01-04T03:27:24+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,198515780,38,Missing code in chapter 11,"Hi, below code is from the book but missing in the cell **In[17]** of ch11.ipynb.

`row_clusters = linkage(df.values, method='complete', metric='euclidean')`

![capture](https://cloud.githubusercontent.com/assets/1693094/21614938/7eadd078-d216-11e6-9b2c-3963b13cf4e4.PNG)
",austinwang0307,1693094,closed,False,1,2017-01-03T16:45:30+00:00,2017-01-04T03:28:28+00:00,2017-01-04T03:27:24+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,195326389,37,small typo,"At Second last paragraph - changed statement from ""now way around"" -> ""no way around""",nipunsadvilkar,15062408,closed,False,1,2016-12-13T18:07:26+00:00,2016-12-13T18:44:59+00:00,2016-12-13T18:44:59+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,195025272,36,minor typos.,,mastash3ff,3743196,closed,False,1,2016-12-12T16:50:05+00:00,2016-12-12T18:10:06+00:00,2016-12-12T18:10:06+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,193362420,35,Master,,dreamylch,22042003,closed,False,1,2016-12-04T17:15:43+00:00,2016-12-05T04:12:12+00:00,2016-12-05T04:12:05+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,191890784,34,Chapter 9 live demo not working,"Hi, 
The link to the live example application ( http://raschkas.pythonanywhere.com/ ) is not working.
There's a ""Coming soon"" message, as if the page did not exist.
",tagwato,11979069,closed,False,1,2016-11-27T22:37:10+00:00,2016-11-28T00:14:05+00:00,2016-11-28T00:14:05+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,188855077,33,New2,,rasbt,5618407,closed,False,0,2016-11-11T21:29:50+00:00,2016-11-11T21:29:54+00:00,2016-11-11T21:29:54+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,183701810,32,small readme typo / grammar edit,,asbhat,3885798,closed,False,1,2016-10-18T14:24:26+00:00,2016-10-18T22:53:22+00:00,2016-10-18T22:53:22+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,180627165,31,Error in chapter 8 code,"```
def tokenizer(text):
    return text.split()

from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

from nltk.corpus import stopwords
stop = stopwords.words('english')

X_train = df.loc[:25000,'review'].values
y_train = df.loc[:25000,'sentiment'].values
X_test = df.loc[25000:,'review'].values
y_test = df.loc[25000:,'sentiment'].values
from distutils.version import LooseVersion as Version
from sklearn import __version__ as sklearn_version
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
if Version(sklearn_version) < '0.18':
    from sklearn.grid_search import GridSearchCV
else:
    from sklearn.model_selection import GridSearchCV

tfidf = TfidfVectorizer(strip_accents=None,
                        lowercase=False,
                        preprocessor=None)

param_grid = [{'vect__ngram_range': [(1, 1)],
               'vect__stop_words': [stop, None],
               'vect__tokenizer': [tokenizer, tokenizer_porter],
               'clf__penalty': ['l1', 'l2'],
               'clf__C': [1.0, 10.0, 100.0]},
              {'vect__ngram_range': [(1, 1)],
               'vect__stop_words': [stop, None],
               'vect__tokenizer': [tokenizer, tokenizer_porter],
               'vect__use_idf':[False],
               'vect__norm':[None],
               'clf__penalty': ['l1', 'l2'],
               'clf__C': [1.0, 10.0, 100.0]},
              ]

lr_tfidf = Pipeline([('vect', tfidf),
                     ('clf', LogisticRegression(random_state=0))])

gs_lr_tfidf = GridSearchCV(lr_tfidf, param_grid,
                           scoring='accuracy',
                           cv=5,
                           verbose=1,
                           n_jobs=-1)
gs_lr_tfidf.fit(X_train,y_train)
```

Hi,
I get an error about ""can't get attribute tokenizer_porter"" ,
what's the problem you think?
",ghost,10137,closed,False,11,2016-10-03T12:22:53+00:00,2017-04-09T16:07:35+00:00,2017-04-09T16:07:35+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,180209635,30,Scikit-learn 0.18 optional syntax,"Added a compatibility layer that supports the new syntax (code is fully backwards compatible)
",rasbt,5618407,closed,False,0,2016-09-30T03:01:24+00:00,2016-09-30T03:01:38+00:00,2016-09-30T03:01:38+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,179671946,29,Master,,dreamylch,22042003,closed,False,4,2016-09-28T03:27:50+00:00,2016-10-06T05:01:20+00:00,2016-10-06T05:01:04+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,177571541,28,Cannot run a line of code,"When I run this script in python notebook:

https://github.com/rasbt/python-machine-learning-book/blob/master/code/optional-py-scripts/ch02.py

The last line (ada.partial_fit(X_std[0, :], y[0])) gives the error:

<**main**.AdalineSGD at 0x10a89fac8>
",Surry47,22256125,closed,False,1,2016-09-17T11:48:42+00:00,2016-09-17T16:51:44+00:00,2016-09-17T16:51:44+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,172268451,27,"Chapter 2 (Rosenblatt Perceptron): ""misclassifications per epochs"" on p. 30 are misleading","First things first: I absolutely like how you motivate, introduce and implement the relevant concepts in your book.

I think there is a problem with the Rosenblatt perceptron learning description (evaluation) as presented in the Figure on page 30 in the book. The errors that are counted in the variable `errors` are the number of updates that are performed in one epoch. However, this number does not represent the number of misclassifications after each epoch.  For instance, if you use your standard options but train only for one iteration, there will be two updates (""2 errors"" according to your terminology), however, all items will be classified as -1 (Setosas), therefore, there are 50 misclassification and this classifier's error rate is actually 50%.

![image](https://cloud.githubusercontent.com/assets/3041168/17831059/9db4f584-66df-11e6-8e3c-082114cac24f.png)
",simon-clematide,3041168,closed,False,5,2016-08-20T12:17:17+00:00,2016-09-01T04:00:49+00:00,2016-08-23T07:01:39+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,168377301,26,Performing hierarchical clustering on a distance matrix,"I understood the concept of complete linkage .. however in the example you provided I did not understand the values in the table with columns 'row label 1', 'row label 2' etc .. 
1. For example what do the numbers (0-7) under the first two columns : 'row label _' represent? 
2. On the first step to create clusters, when you just have points, how do you go about creating clusters? You attempted to explain that via the example, but if you could expand on your example I would really appreciate it.
",VedAustin,3083310,closed,False,4,2016-07-29T17:46:00+00:00,2016-07-31T03:47:47+00:00,2016-07-31T03:47:47+00:00,question,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,166921285,25,Kernal PCA [projecting new data points],"So you have this:

```
X, y = make_moons(n_samples=100, random_state=123)
alphas, lambdas =rbf_kernel_pca(X, gamma=15, n_components=1)
```

Then you take a sample from X:
`x_new = X[25]`

And then find the projection for the new sample from:

```
x_reproj = project_x(x_new, X, 
...       gamma=15, alphas=alphas, lambdas=lambdas)
```

But `x_new` was already a part of alphas and lambdas created using X. In other words, X already had x_new when the rbf_kernel_pca was applied. So should I be surprised that the projected value of x_new coincides exactly in the plots? I would have thought it might have been better to exclude x_new to derive alpha and lambda values and then apply `project_x`. Thoughts?
",VedAustin,3083310,closed,False,3,2016-07-21T21:24:13+00:00,2016-07-27T04:45:03+00:00,2016-07-26T20:40:25+00:00,question,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,166434785,24,Chapter: Combining weak to strong learners via random forests [sample size],"> Via the sample size n of the bootstrap sample, we control the bias-variance tradeoff of the random forest. By choosing a larger value for n, we decrease the randomness and thus the forest is more likely to overfit. On the other hand, we can reduce the degree of overfitting by choosing smaller values for n at the expense of the model performance. 

To me this implies that I should choose sample size n, that is smaller than N (original training set size).

> In most implementations, including the RandomForestClassifier implementation in scikit-learn, the sample size of the bootstrap sample is chosen to be equal to the number of samples in the original training set, which usually provides a good bias-variance tradeoff

But the above got me confused: If we choose n = N, then aren't we overfitting unless the algorithm is bootstrapping aggressively - repeating the values many times over?
",VedAustin,3083310,closed,False,3,2016-07-19T21:02:17+00:00,2016-07-27T04:42:22+00:00,2016-07-26T20:24:41+00:00,question,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,166326077,23,Reinforcement Learning - Where Art Thou?,"Wonderful book; learning a ton! Question: In first chapter, you explain the three types of learning (supervised, unsupervised and reinforcement). Usually the third is not listed. So, I search your text for other material on RL but found none. Future chapter in next edition? Future book? In your other resources, are there links about RL with a scikit-learn style? Love [Karpathy's blog](https://karpathy.github.io/2016/05/31/rl/) on ""Pong from Pixels"". 
",Hackathorn,443988,closed,False,1,2016-07-19T13:04:45+00:00,2016-07-20T20:12:39+00:00,2016-07-20T20:12:17+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,165647100,22,Numpy Future Warning when using plot_decision_regions function,"Sebastian,

I've been collecting my own data and have applied the plot_decision_regions function several times to my data but I am running into a problem with this new data. The problem is occurring here:

```
#plot class samples
    for idx, cl in enumerate(np.unique(y)):
        plt.scatter(x=X[y == cl, 0], y=X[y == cl, 1],
                    alpha=0.8, c=cmap(idx),
                    marker=markers[idx], label=cl)
```

My enumerated object is: [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]
So 5 classifications hot encoded.

From what I understand, this list comprehension passes over my X_train_pca data five times and uses the boolean comparison y == cl to plot all my data points with five different colors as it passes through the markers and colormap.

Upon running, I get the warning:

FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  plt.scatter(x=X[y == cl, 0], y=X[y == cl, 1],

The really weird part is the values in the array: X[y==cl, 0]
They now look like: [-0.4277726  -0.4277726  -0.44362509 ..., -0.4277726  -0.4277726  -0.4277726 ]
With shape (9784,) which is the original length of my X_train_pca data. (I believe it should be closer to about a fifth since most of my data is similar in length and I checked np.shape after the loop ran.)

To give a visual my data looks like this.

![image](https://cloud.githubusercontent.com/assets/17873279/16853839/38f5f474-49dc-11e6-8eb7-f0443cf95660.png)

When it should be separated into colors with a spread looking like this.

![image](https://cloud.githubusercontent.com/assets/17873279/16853892/7e218bb2-49dc-11e6-887a-426d357f9442.png)

I can't really think through the problem anymore probably due to a misunderstanding of what this future warning is trying to tell me. I am wondering if you have any ideas as to what might cause this behavior.
",seth814,17873279,closed,False,3,2016-07-14T20:07:06+00:00,2016-07-16T04:21:37+00:00,2016-07-16T01:23:05+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,165226743,21,Add Code Examples,"Just bought this book and I can't find the source code of the examples in the book. I bought on Amazon and gone to Packtpub page as suggested on the book but even the zip I download from them is only a mirror to this repository. Just images, no code for the examples in the book. It's really annoying to have to type every single example by hand.
",andrelip,1043693,closed,False,3,2016-07-13T03:04:15+00:00,2016-07-18T19:52:37+00:00,2016-07-18T19:52:37+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,164511425,20,changed model scoring value from 0.98 to 0.95,"Typo: model scoring should be 0.95
",NeerajSarwan,11672269,closed,False,1,2016-07-08T11:25:49+00:00,2016-07-13T03:29:49+00:00,2016-07-13T03:29:46+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,163592818,19,Update difference-deep-and-normal-learning.md,"Fix typo imagine => image
",SumitBando,248569,closed,False,1,2016-07-04T02:20:04+00:00,2016-07-04T15:43:26+00:00,2016-07-04T15:43:24+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,163016712,18,Cant import using pickle ch9,"When i try to read back the classifier on page 254 i get the following error. I have done like in the book the whole way and things have worked find until now. Any idea what has gone wrong?

Im using ipython 4.2.0

```
AttributeError                            Traceback (most recent call last)
<ipython-input-4-f050da95a5cf> in <module>()
----> 1 import codecs, os;__pyfile = codecs.open('''/var/folders/yh/mm1bdmx9073_b15lw69b2qmh0000gn/T/py71220g7y''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/yh/mm1bdmx9073_b15lw69b2qmh0000gn/T/py71220g7y''');exec(compile(__code, '''/Users/henke/Documents/code/python/python-ml/movieclassifier/main.py''', 'exec'));

/Users/henke/Documents/code/python/python-ml/movieclassifier/main.py in <module>()
      4 from vectorizer import vect
      5 
----> 6 clf = pickle.load(open(os.path.join('pkl_objects', 'classifier.pkl'), 'rb'))
      7 
      8 import numpy as np

AttributeError: Can't get attribute 'tokenizer' on <module '__main__'>
```
",favetelinguis,5941745,closed,False,3,2016-06-29T20:17:32+00:00,2016-06-30T17:00:19+00:00,2016-06-30T15:57:35+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,162304680,17,Rewrote the last sentence introducing lambda,"And also fixed a mis-spelling of ""constrained"" at the end of the page.
",erikr,1253422,closed,False,1,2016-06-25T23:33:24+00:00,2016-06-26T08:18:33+00:00,2016-06-26T08:18:33+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,162304529,16,typo: missing word,"I think ""term"" should be added there.
",erikr,1253422,closed,False,1,2016-06-25T23:27:37+00:00,2016-06-26T08:08:33+00:00,2016-06-26T08:08:31+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,161404612,15,fix typo,"one of he work horses of Data Mining --> one of the work horses of Data Mining
",lxj616,12285589,closed,False,1,2016-06-21T10:46:03+00:00,2016-06-24T23:55:26+00:00,2016-06-24T23:55:26+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,160106825,14,Chapter 2: confusion b/w perceptron code and SGD code,"In the perceptron part of the code, I see:

```
for xi, target in zip(X, y):
  update = self.eta * (target - self.predict(xi))
  self.w_[1:] += update * xi
  self.w_[0] += update
```

In the SGD part I see something similar except that everytime the new gradient point is calculated, the data is shuffled:

```
X, y = self._shuffle(X, y)
for xi, target in zip(X, y):
  cost.append(self._update_weights(xi, target))
```

```
def _update_weights(self, xi, target):
  """"""Apply Adaline learning rule to update the weights""""""
  output = self.net_input(xi)
  error = (target - output)
  self.w_[1:] += self.eta * xi.dot(error)
  self.w_[0] += self.eta * error
```

I do not see any difference between the two except for the shuffling part and the part that one is binary value and the other is a real value (SGD). Did I misunderstand how fundamentally the weights are calculated for SGD and simple perceptron model. Ofcourse if there was a mini batch implementation, the code would have looked a lot more like adaptive linear neurons. But since you are taking sample by sample, they are implemented similarly?
",VedAustin,3083310,closed,False,3,2016-06-14T06:31:49+00:00,2016-06-15T22:37:03+00:00,2016-06-15T06:07:04+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,158569333,13,Better question and answer for deep learning FAQ,,BoltzmannBrain,8323700,closed,False,5,2016-06-05T19:15:26+00:00,2016-06-09T14:22:11+00:00,2016-06-09T02:40:36+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,158568167,12,Updates difference-deep-and-normal-learning.md,"Fixes to grammatical errors
",shashankgroovy,981895,closed,False,4,2016-06-05T18:48:53+00:00,2016-06-07T17:36:56+00:00,2016-06-05T19:00:54+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,158562511,11,Update difference-deep-and-normal-learning.md,"fixing typo
",Bachmann1234,1521093,closed,False,1,2016-06-05T16:32:58+00:00,2016-06-05T17:13:44+00:00,2016-06-05T17:13:44+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,158512746,10,SoftmaxRegression - zero_init_weight missing,"Hello,
I think the function  zero_init_weight is missing.
I searched the github site but did not find it.
Maybe this is another version of the softmax-regressor and here it is missing?

Best Regards, Thomas
",theiling,7579722,closed,False,1,2016-06-04T16:42:09+00:00,2016-06-06T00:11:23+00:00,2016-06-06T00:11:23+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,157301794,9,Incorrect results printed for MLPGradientCheck,"I was running MLPGradientCheck, but the results are different from example
When I tried to locate the problem, I found that a3 in MLPGradientCheck.fit is always ""nan""
Is that normal? how could I fix it

![problem](https://cloud.githubusercontent.com/assets/15005793/15622696/56ae54fc-2439-11e6-9c94-d8a5e55cdf17.png)
",zhangzfmail,15005793,closed,False,1,2016-05-27T22:32:25+00:00,2016-05-27T23:43:46+00:00,2016-05-27T23:43:46+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,157284436,8,"operands could not be broadcast together with shapes (5,5) (10,5)","I am trying to execute MLPGradientCheck.fit in chapter 12
But got an error
The code is copied from source code in Chapter 12 
Could you please tell me where I am wrong and how to fix it?

![error](https://cloud.githubusercontent.com/assets/15005793/15620239/23b0cc90-2427-11e6-9bed-f0a7717ba837.png)
",zhangzfmail,15005793,closed,False,25,2016-05-27T20:25:31+00:00,2020-05-28T14:39:57+00:00,2016-05-30T17:26:21+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,151228037,7,Updated ebook not yet available from O'Reilly,"Just a heads up on this -- I checked my O'Reilly account, and they did not yet have the updated version.

I'll post here once it appears.
",gbuesing,6653,closed,False,12,2016-04-26T20:12:23+00:00,2016-04-29T20:09:59+00:00,2016-04-29T14:13:50+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,145070857,6,Confusion in chapter 2,"In chapter 2 you have some code for a simple perceptron model.

On page 27, you describe the code. 

> the `net_input` method simply calculates the vector product wTx

However, there is more than a simple vector product in the code:

```
def net_input(self, X):
    """"""Calculate net input""""""
    return np.dot(X, self.w_[1:]) + self.w_[0]
```

In addition to the dot product, there is an addition. The text does not mention anything about what is this `+ self.w_[0]`

Can you (or anyone) explain why that's there?

thanks,
-trevor
",tmsimont,1643712,closed,False,12,2016-04-01T02:47:03+00:00,2017-06-15T04:34:58+00:00,2016-04-01T03:35:45+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,142253399,5,Broken link in FAQ,"In 

> General Questions section of  FAQ

**How do Data Scientists perform model selection? Is it different from Kaggle?**

The web link is broken.

Thank you for the beautiful book.
",Amrithasuresh,17560009,closed,False,1,2016-03-21T04:26:25+00:00,2016-03-21T17:57:08+00:00,2016-03-21T17:57:08+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,139076811,4,fix faq 'Pyhon' typo,,MTietze,3495618,closed,False,1,2016-03-07T19:55:03+00:00,2016-03-07T22:04:18+00:00,2016-03-07T22:04:08+00:00,,0,0,0,0,0,0,0
rasbt/python-machine-learning-book,137809562,3,Errata update question,"Regarding your remark:

> [2015-10-20] Good news! I just heard back from the publisher; all the typos and errors which are listed below will be fixed by next week.

I bought the ebook yesterday (O'Reilly, not PACKT) and found some errors. Up to now, they are in the errata (v2), but not yet fixed in my fresh copy.  Can you say something about the current state, are the updates for immediate PACKT customers only?

edit: 
Interestingly, my copy stands the test on page viii (so I have _Classifiers_ there), but for example not the one regarding the inverted _'y'_ variants (with and w/o caret) on page 22 and also the following errors (p. 23) are still present.
",traits,4024583,closed,False,7,2016-03-02T08:44:28+00:00,2016-04-27T20:50:39+00:00,2016-04-27T20:50:39+00:00,,0,0,0,0,0,0,0
