repo_full_name,issue_id,number,title,body,user_login,user_id,state,locked,comments_count,created_at,updated_at,closed_at,labels,reactions_total,reactions_plus1,reactions_minus1,reactions_laugh,reactions_hooray,reactions_confused,reactions_heart
ydataai/ydata-profiling,3045852823,1759,KeyError: 'n_invalid_dates' from report_html,"### Current Behaviour

I have following dataframe:
`df:pyspark.sql.dataframe.DataFrame
tpep_pickup_datetime:timestamp
tpep_dropoff_datetime:timestamp
trip_distance:double
fare_amount:double
pickup_zip:integer
dropoff_zip:integer
id:long`
 
When I apply the following code:
` report = ProfileReport(
        df,
        title=dataset_name,
        infer_dtypes=False,
        interactions=None,
        missing_diagrams=None,
        correlations={
            ""auto"": {""calculate"": False},
            ""pearson"": {""calculate"": True},
            ""spearman"": {""calculate"": True},
        },
    )
    
    # Convert profiling to JSON
    profiling_json = json.loads(report.to_json())
   
    report_html = report.to_html()

    displayHTML(report_html)`

I am getting key error in the title.  When I drop the date columns, I can reach HTML view. 


### Expected Behaviour

But I need date columns profiling HTML result, too. What should I do?

### Data Description

This is my dataframe: 
```
f:pyspark.sql.dataframe.DataFrame
tpep_pickup_datetime:timestamp
tpep_dropoff_datetime:timestamp
trip_distance:double
fare_amount:double
pickup_zip:integer
dropoff_zip:integer
id:long
```

### Code that reproduces the bug

```Python
KeyError: 'n_invalid_dates'
table2 = Table(
     62     [
     63         {""name"": ""Minimum"", ""value"": fmt(summary[""min""]), ""alert"": False},
     64         {""name"": ""Maximum"", ""value"": fmt(summary[""max""]), ""alert"": False},
     65         {
     66             ""name"": ""Invalid dates"",
---> 67             ""value"": fmt(summary[""n_invalid_dates""]),
     68             ""alert"": False,
     69         },
     70         {
     71             ""name"": ""Invalid dates (%)"",
     72             ""value"": fmt_percent(summary[""p_invalid_dates""]),
     73             ""alert"": False,
     74         },
     75     ],
```

### pandas-profiling version

%pip install ydata-profiling==4.16.1

### Dependencies

```Text
!pip install great_expectations==1.4.2
Python >=3.10
```

### OS

_No response_

### Checklist

- [x] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [x] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [x] The issue has not been resolved by the entries listed under [Common Issues](https://docs.profiling.ydata.ai/latest/support-contribution/contribution_guidelines/).",aysegulcayir,49029525,open,False,0,2025-05-07T12:46:29+00:00,2025-05-07T12:46:42+00:00,,needs-triage,0,0,0,0,0,0,0
ydataai/ydata-profiling,3030853013,1758,fix: refactor datetime to remove deprecation warnings,"# PR Summary
This small PR fixes the `datetime` deprecation warnings which you can find in the CI logs:
```python
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    date_start = datetime.utcnow()
```",emmanuel-ferdman,35470921,open,False,0,2025-04-30T10:27:13+00:00,2025-04-30T10:27:13+00:00,,,0,0,0,0,0,0,0
